######################
# MAIN CONFIGURATION #
######################

# Delay before the servers stops in minutes
stop_delay: 1

# Command used to stop servers
# Do not change unless you know what you're doing
# Useful in case you start servers in a detached screen
stop_command: "stop\n"  # For the \n to work, must be between quotes ""

# Amount of servers that the plugin can start
# Set to <= 0 for no limit
max_servers: 1

###################
# HTTP API SERVER #
###################

# Enable HTTP server to manage the servers
# Set to <= 0 to disable
http_port: -1

#####################
# SERVER ON THE FLY #
#####################

# Enable this to allow creation of servers on the fly via /odscreate command or API if enabled
allow_server_on_the_fly: false

# Path where the new servers will be created, the folder must exists
server_folder: '/servers/on_the_fly'

# Template servers for the on the fly servers
templates: '/servers/templates'

port_range: 25566-25599

#################
# PROXY SERVERS #
#################

# Syntax: [server name]: [command to start the server]
servers:
  # This is an example for a server named "lobby" hosted on the same Windows machine as the proxy
  test:
    # Directory where the server is located, can be relative or absolute
    directory: '/servers/test'
    # Name of the jar file
    jar_file: 'paper.jar'

    # Optional, maximum memory in MB
    maximum_memory: 8192

    # Optional, minimum memory in MB to start the server with
    minimum_memory: 2048

    # Optional, custom JVM arguments, the example uses Aikar's flags https://mcflags.emc.gs/
    jvm_arguments: '-XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true'

    # Optional, setting this parameter to true will bypass the start cooldown of the server when using an old version of spigot.
    # Works only for Spigot and its derivatives
    IReallyKnowWhatIAmDoingISwear: true